spring.application.name=product-processing-unit

server.port=8081

eureka.client.service-url.defaultZone=${EUREKA_URL:http://10.131.254.83:8761/eureka/}
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=${HOST_IP:10.131.254.254}

spring.data.redis.host=${REDIS_HOST:10.131.254.83}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.database=0

management.endpoints.web.exposure.include=health,info
